CREATE TABLE USERS (
  ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  USER_NAME VARCHAR2(20) NOT NULL UNIQUE,
  USER_PASSWORD CHAR(60) NOT NULL,
  USER_ROLE NUMBER(1) NOT NULL
);

CREATE TABLE ATTENDANCE (
  ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  USER_ID NUMBER NOT NULL,
  WORK_DATE DATE NOT NULL,
  CLOCK_IN DATE,
  CLOCK_OUT DATE,
  CONSTRAINT FK_ATT_USER FOREIGN KEY (USER_ID) REFERENCES USERS(ID),
  CONSTRAINT UK_ATT_USER_DATE UNIQUE (USER_ID, WORK_DATE)
);
